config/routes.rb
Rails.application.routes.draw do
  #Employee Routes

  get 'employees', to: 'employees#index'
  get 'employees/new', to: 'employees#new',as: :new_employee
  post 'employees', to: 'employees#create',as: :create_employee 
  get 'employees/edit/:id', to: 'employees#edit',as: :edit_employee
  patch 'employees/:id', to: 'employees#update',as: :update_employee
  delete 'employees/:id', to: 'employees#destroy',as: :delete_employee
  get 'employees/emp', to: 'employees#emp',as: :employee
  # get 'employees/:id', to: 'employees#show',as: :employee
  
  #Project Routes

  get 'projects', to: 'projects#index'
  get 'projects/new', to: 'projects#new',as: :new_project
  post 'projects', to: 'projects#create',as: :create_project 
  get 'projects/:id/edit', to: 'projects#edit',as: :edit_project
  patch 'projects/:id', to: 'projects#update',as: :update_project 
  delete 'projects/:id', to: 'projects#destroy',as: :delete_project
  get 'projects/proj', to: 'projects#proj',as: :project 
  # get 'projects/:id', to: 'projects#show',as: :project 

  #Employeeprojects Routes

  get 'employeeprojects', to: 'employeeprojects#index'
  # get 'employeeprojects', to: 'employeeprojects#show',as: :employeeproject

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :employee_project, dependent: :destroy
  has_many :projects, through: :employee_project
end

app/models/employee_project.rb
class EmployeeProject < ApplicationRecord
  belongs_to :employee
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :employee_project, dependent: :destroy
  has_many :employees, through: :employee_project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_path
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    @employee.update(employee_params)
    redirect_to employees_path
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_path
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def emp
    @emprojs = EmployeeProject.all
  end

  private
  def employee_params
    params.require(:employee).permit(:name)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to projects_path
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  def show
    @project = Project.find(params[:id])
  end

  def proj
    @emprojs = EmployeeProject.all
  end

  private
  def project_params
    params.require(:project).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/employees/edit.html.erb
<center>
  <h1>Edit Employees</h1>
  <%= form_for @employee do |form|%>
    <%= form.text_field :name %><br>
    <% @employee.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <%= form.submit %>
  <% end %>
</center>

app/views/employees/emp.html.erb
<center>
  <h1>Projects</h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Project_Id</th>
      </tr>
    </thead>
    <tbody>
      <% @emprojs.each do |e|%>
        <tr>
          <td><%= e.project.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</center>

app/views/employees/index.html.erb
<center>
  <h1><td>Employee</td></h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
        <th scope="col">Show</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee|%>
        <tr>
          <td><%= employee.name %></td>
          
          <td><%= link_to 'Edit', edit_employee_path(employee.id), method: :get %></td>
          <td><%= link_to 'Delete', delete_employee_path(employee.id), method: :delete %></td>
          <td><%= link_to 'Show', employee_path(employee.id), method: :get %></td>
        </tr>  
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'Employee', employee_path %>
  <br>
  <%= link_to 'New Emp', new_employee_path %>
  <br>
  <%= link_to 'Project', projects_path %>

app/views/employees/new.html.erb
<center>
  <h1>New Employees</h1>

  <%= form_for @employee do |form|%>
    <%= form.text_field :name %><br>
    <% @employee.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <%= form.submit %>
  <% end %>
</center>

app/views/employees/show.html.erb
<center><h1>Employee Name: <br><u><%= @employee.name %></h1><center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-2">
          <div id="side"><br>
         
          </div>
          <div id="main">
            <%= @content_for_layout %>
          </div>
        </div>
        <div class="col-6">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/projects/edit.html.erb
<center>
  <h1>Edit Employees</h1>
  <%= form_for @project do |form|%>
    <%= form.text_field :name %><br>
    <% @project.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <%= form.submit %>
  <% end %>
</center>

app/views/projects/index.html.erb
<center>
  <h1>Projects</h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Name</th>
      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project|%>
        <tr>
          <td><%= project.name %></td>
          <td><%= link_to 'Edit', edit_project_path(project.id), method: :get %></td>
          <td><%= link_to 'Delete', delete_project_path(project.id), method: :delete %></td>
          <td><%= link_to 'Show', project_path(project.id), method: :get %></td>
        </tr>  
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'Project', project_path %>
  <br>
  <%= link_to 'New Project', new_project_path %>
</center>

app/views/projects/new.html.erb
<center>
  <h1>New Projects</h1>

  <%= form_for @project do |form|%>
    <%= form.text_field :name %><br>
    <% @project.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
    <%= form.submit %>
  <% end %>
</center>

app/views/projects/proj.html.erb
<center>
  <h1>Projects</h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Employee_Name</th>
      </tr>
    </thead>
    <tbody>
      <% @emprojs.each do |e|%>
        <tr>
          <td><%= e.employee.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</center>

app/views/projects/show.html.erb
<center><h1>Project Name: <br><u><%= @project.name %></h1><center>